CREATE TABLE `user`(
   `id` BIGINT(20) UNSIGNED AUTO_INCREMENT COMMENT '主键 id',
   `user_name` VARCHAR(100) NOT NULL COMMENT '用户名',
   `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
   `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
   PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '用户表';


CREATE TABLE `wallet`(
   `id` BIGINT(20) UNSIGNED AUTO_INCREMENT COMMENT '主键 id',
   `user_id` BIGINT(20) NOT NULL COMMENT '用户id',
   `balance` BIGINT(20) NOT NULL COMMENT '余额',
   `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
   `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
   PRIMARY KEY ( `id` ),
   UNIQUE KEY (`user_id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '钱包表';


CREATE TABLE `balance_change_detail`(
   `id` BIGINT(20) UNSIGNED AUTO_INCREMENT COMMENT '主键 id',
   `wallet_id` BIGINT(20) NOT NULL COMMENT '钱包id',
   `order_id` BIGINT(20) DEFAULT NULL COMMENT '关联订单id',
   `change_amount` BIGINT(20) NOT NULL COMMENT '金额变更数量',
   `after_change_amount` BIGINT(20) NOT NULL COMMENT '余额变更后数量',
   `change_type` INT(2) NOT NULL COMMENT '变更类型 1:充值 2:提现 3:消费 4:退款',
   `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
   `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
   PRIMARY KEY ( `id` ),
   INDEX wallet_id (`wallet_id`),
   INDEX order_id (`order_id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '钱包金额变更明细表';


CREATE TABLE `order`(
   `id` BIGINT(20) UNSIGNED AUTO_INCREMENT COMMENT '主键 id',
   `price` BIGINT(20) NOT NULL COMMENT '价格',
   `status` INT(2) NOT NULL COMMENT '订单状态 1:未付款 2:付款中 3:已付款 4:已退款',
   `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
   `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
   PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '订单表';